name: "KBAnalysis"
description: "An action to analyze action"
inputs:
  issue-id:
    description: "ID of newly created KB issue"
    required: true 
  github-token:
    description: "github-token to be used for octokit authentication"
    required: true
    default: "${{github.token}}"
    

runs:
  using: node16
  main: dist/src/index.js


